### ISSUE TITLE
[Bug/Crash]: Discord SDK fails to load GDExtension

### ISSUE THREAD

**Issue by ltecheroffical** [vaporvee/discord-rpc-godot#44]
### What happened?

When I installed the SDK I expected it to start and let me run it but when I installed it I just get errors saying "GDExtension dynamic library not found: /Users/.../Developer/Projects/Godot/.../addons/discord-sdk-gd/bin/macos/" and it doesn't load, I have no idea how to fix 

### Version

3.2

### Godot Version

4.2

### GDScript

```gdscript
N/A
```

### Godot output

```shell
Can't open dynamic library: /Users/…/Developer/Projects/Godot/.../addons/discord-sdk-gd/bin/macos/libdiscord_game_sdk_binding_debug.dylib. Error: dlopen(/Users/.../Developer/Projects/Godot/.../addons/discord-sdk-gd/bin/macos/libdiscord_game_sdk_binding_debug.dylib, 2): Library not loaded: @rpath/discord_game_sdk.dylib
    Referenced from: /Users/.../Developer/Projects/Godot/.../addons/discord-sdk-gd/bin/macos/libdiscord_game_sdk_binding_debug.dylib
    Reason: image not found.
  core/extension/gdextension.cpp:719 - GDExtension dynamic library not found: /Users/.../Developer/Projects/Godot/.../addons/discord-sdk-gd/bin/macos/libdiscord_game_sdk_binding_debug.dylib
  Failed loading resource: res://addons/discord-sdk-gd/bin/discord-rpc-gd.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.

**Comment by vaporvee** [comment]
yeah on mac obviously 
https://github.com/vaporvee/discord-sdk-godot/wiki/Building#macos-support
