### ISSUE TITLE
[Issue/Bug]: DRG RPC not showing in discord (using windows 11 and default discord client, with demo project)

### ISSUE THREAD

**Issue by alyxeo2k** [vaporvee/discord-rpc-godot#56]
### What happened?

the RPC doesnt show in discord either on linux nor windows 11

### Version

1.3.1

### Godot Version

4.2.1

### Exact steps to reproduce this error

- Launch demo project
- Check activity on discord

### GDScript

```gdscript
none
```

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.
- [X] I did read the documentation https://vaporvee.com/docs/discord-rpc-godot/

**Comment by vaporvee** [comment]
so how exactly should you show an activity rpc when you don't even have written a single line of gdscript

**Comment by vaporvee** [comment]
the reason you should submit a ticket here is that i want to look at your code but its not that easy when you don't provide any

**Comment by vaporvee** [comment]
and if it still also doesn't work on the demo please check the activity privacy setting in your discord

**Comment by alyxeo2k** [comment]
> and if it still also doesn't work on the demo please check the activity privacy setting in your discord

This fixed it, I didn't have one of the settings checked 😅

**Comment by vaporvee** [comment]
yeah i should probably add that to the faq lol
