### ISSUE TITLE
[Issue/Bug]: Parse error when launching a game with DiscordRPC, even with checks to disable running DiscordRPC in place.

### ISSUE THREAD

**Issue by sourcelocation** [vaporvee/discord-rpc-godot#58]
### What happened?

When launching the game on mobile, it crashes while parsing the file where I'm using DiscordRPC, even with checks to avoid running the code on mobile.

### Version

1.3.1

### Godot Version

4.2.1

### Exact steps to reproduce this error

Use DiscordRPC on mobile, but don't run it. You will get this error
![image](https://github.com/vaporvee/discord-rpc-godot/assets/52459150/163ffc5c-ba3c-4406-b731-015a75da1250)

### GDScript

```gdscript
func set_up():
	print(OS.get_name()) # prints: Android
	if is_mobile: return
	DiscordRPC.app_id = 1234945200032317602 # Parse Error
```

### Godot output

`No suitable library found for GDExtension: res://addons/discord-rpc-gd/bin/discord-rpc-gd.gdextension. Possible feature flags for your platform: mobile, android, etc2, astc, arm64, template, debug, template_debug`

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.
- [X] I did read the documentation https://vaporvee.com/docs/discord-rpc-godot/

**Comment by vaporvee** [comment]
there is a function to unregister that in GDExtentionManager i think. will send you a solution when I'm at home. on web it doesnt crash never tested it on mobile tbh

**Comment by sourcelocation** [comment]
Thank you, will be waiting

**Comment by vaporvee** [comment]
Sorry for not responding will have time next week

**Comment by sourcelocation** [comment]
No problem, I'm still developing my game to this day.

**Comment by vaporvee** [comment]
Try
```gdscript
if GDExtensionManager.is_extension_loaded("res://addons/discord-rpc-gd/bin/discord-rpc-gd.gdextension"):
```
before loading any part of the plugin also exclude the plugin in the export settings like the following and tell me if it helped. 
![Screenshot 2024-08-08 220332](https://github.com/user-attachments/assets/006086fa-32fa-47db-8c88-d163e2f1fcca)
I don't have the project anymore where i accomplished this but i remember GDExtensionManager is the way.

**Comment by vaporvee** [comment]
the issue is this is just how godot runs gdextensions i can't change that. Is the autoload maybe still running? you should only add the node conataining a script with discord rpc when the plugin is loaded so you cant do
```gdscript
if GDExtensionManager.is_extension_loaded("res://addons/discord-rpc-gd/bin/discord-rpc-gd.gdextension"):
    DiscordRPC.app_id= xyz
```
instead you need to do
```gdscript
if GDExtensionManager.is_extension_loaded("res://addons/discord-rpc-gd/bin/discord-rpc-gd.gdextension"):
    add_child(your_node_with_discord_rpc_xyz)
```

**Comment by Yolwoocle** [comment]
Okay, thank you for your answer. I ended up making a scene for the Discord rich presence, and put something like this in my main autoload, which seems to do the trick. 
```gdscript
func is_discord_rpc_supported() -> bool:
	return game_platform == GamePlatform.PC and GDExtensionManager.is_extension_loaded("res://addons/discord-rpc-gd/bin/discord-rpc-gd.gdextension")

func _init_discord_rpc():
	if not is_discord_rpc_supported():
		return
	
	var discord_rich_presence_scene: PackedScene = load("res://scenes/integration/discord_rich_presence.tscn")
	discord_rich_presence = discord_rich_presence_scene.instantiate()
	add_child(discord_rich_presence)
	
	discord_rich_presence.initialize()
```

**Comment by vaporvee** [comment]
I'll add that to the troubleshooting guide if that's okay :)

**Comment by Yolwoocle** [comment]
> I'll add that to the troubleshooting guide if that's okay :)

Sounds good. Feel free to use my bit of code if needed
