### ISSUE TITLE
[Issue/Bug]: (Editor presence) Godot crashes when creating a new scene.

### ISSUE THREAD

**Issue by TK3D** [vaporvee/discord-rpc-godot#62]
### What happened?

I'm using the plugin only for the editor presence on Discord, not using custom RPC for my game.
With the plugin enabled, Godot crashes as soon as I create a new scene.
After re-opening the project I can create scenes but the plugin isn't working. 
It needs to be toggled off and on again in the Editor settings to work, but then I am back to being unable to create new scenes.

### Version

1.3.1

### Godot Version

4.2.2.stable

### Exact steps to reproduce this error

- Create new project
- Install plugin and enable it
- Restart Godot
- Create new scene

### GDScript

```gdscript
No custom code involved.
```

### Additional information

OS: Manjaro Linux
Kernel: 6.10.3-1-MANJARO (64-bit)
Version: 4.2.2.stable on Steam (Runtime)

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.
- [X] I did read the documentation https://vaporvee.com/docs/discord-rpc-godot/

**Comment by vaporvee** [comment]
Will try to reproduce that next week on linux

**Comment by KuroyukiDev** [comment]
I'm having the same issue but on Windows 11 (64-bit).

**Addon Version:** `1.3.1`
**Godot Version:** `4.3-stable`

**What's the issue I'm having:**
```text
I followed the steps to enable the plugin. 

The steps work thru the 1st restart but it crashes when the loading bar in the files tree pane is still loading the files in the editor.

I've tried deleting the ".godot/" folder to clear the old cache and the editor keeps crashing when I have THIS addon part of the way enabled. I cannot get the addon fully re-enabled in the Autoloads and the restart from enabling the addon doesn't re-enable or re-add the Autoload gd script file.

This never happened to me on Godot 4.2.x but when I upgraded my project from Godot 4.2.x to Godot 4.3-stable this problem started happening.
```

**Comment by vaporvee** [comment]
Can you give me some specs of your hardware? I think i need to get another hook for the editor plugin to startup when its causing issues on different hardware what i assume now after some testing

**Comment by vaporvee** [comment]
No answer
