### ISSUE TITLE
Flatpack support

### ISSUE THREAD

**Issue by SpacePogam** [vaporvee/discord-rpc-godot#66]
### What happened?

Using the example code to make the Discord RPC function, my game doesn't seem to detect Discord at all, instead returning the error:
Discord Activity couldn't be updated. It could be that Discord isn't running!
Discord is very much running, actually. I assume the same problem occurs in the Demo export, which also doesn't show the rich presence.

### Version

1.3.1

### Godot Version

4.3

### Exact steps to reproduce this error

- Download 1.3.1 and extract into an addons folder, enable the plugin for the project.
- Use the quick start code in a ready function on a script that autoloads, changing the values to match your own application.
- Run the project and receive an error (yippee!)

### GDScript

```gdscript
extends Node

func _ready():
	DiscordRPC.app_id = 1278828534357295104
	DiscordRPC.details = "details, wow"
	DiscordRPC.state = "death"
	DiscordRPC.large_image = "logo-rpc"
	DiscordRPC.large_image_text = "Debugging hard..."
	DiscordRPC.small_image = "logo-rpc"
	DiscordRPC.small_image_text = "golly gee"

	DiscordRPC.start_timestamp = int(Time.get_unix_time_from_system())
	
	DiscordRPC.refresh()
```

### Godot output

```shell
W 0:00:00:0664   discord.gd:14 @ _ready(): Discord Activity couldn't be updated. It could be that Discord isn't running!
  <C++ Source>   core/variant/variant_utility.cpp:1112 @ push_warning()
  <Stack Trace>  discord.gd:14 @ _ready()
```

### Additional information

I am using Linux Mint 21.2 Cinnamon, Discord is from Flatpak and Godot is from Steam.

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.
- [X] I did read the documentation https://vaporvee.com/docs/discord-rpc-godot/

**Comment by vaporvee** [comment]
Try the demo-export from the releases if that doesn't show up try to load discord without loading flatpack. If it does you did something wrong in your project. and if it still doesn't i need to update the troubleshooting guide because the next fix is annoying to type everytime

**Comment by SpacePogam** [comment]
Hey, I ran the code using the Debian image install of Discord and it ended up working. I don't really expect it to happen super soon, but would it be possible for this addon to work with the Flatpak version in the future?
![image](https://github.com/user-attachments/assets/ef0d1b76-0b65-400d-ba34-78427a8b8d6d)

**Comment by vaporvee** [comment]
I dont even know if its possible but will look into it

**Comment by vaporvee** [comment]
There is a workaround in the troubleshooting guide
