### ISSUE TITLE
[Feature request]: Mobile Support

### ISSUE THREAD

**Issue by TheNetherPug** [vaporvee/discord-rpc-godot#67]
### What is your idea?

I'd really like to see mobile support added in this addon. Currently as it stands, the addon does not load when running as a mobile application. This has the unfortunate side-effect of crashing the application whenever a script uses the DiscordRPC singleton.

**Comment by vaporvee** [comment]
#54 

actual mobile support is not possible with discord's library

**Comment by TheNetherPug** [comment]
> #58
> 
> actual mobile support is not possible with discord's library

Oh ok
