### ISSUE TITLE
[Issue/Bug]: get_is_discord_working is always false

### ISSUE THREAD

**Issue by Variable-ind** [vaporvee/discord-rpc-godot#68]
### What happened?

Hy, i wanted to implement discord rpc to a project, but the `get_is_discord_working()` always returns false no matter what i do (the value of `result` is 4).

i even tried it with the example code in DiscordRPCTutorial class. but still the same error (This time i am using an empty project with just the add-on installed and enabled).

Please help

https://github.com/user-attachments/assets/0830c9bf-0dd9-499b-8d69-e3f626a22a27

### Version

1.3.1

### Godot Version

4.3 stable

### Exact steps to reproduce this error

in video

### GDScript

```gdscript
class_name DiscordRPCTutorial
extends Node

## 1. Put the addons/ folder in your Godot project[br]
## 2. Enable the addon in your Project Settings under "Plugins" and "DiscordRPC". [br](if it doesn't show up restart your project and try again)[br]
## 3. Restart your project[br]
## 4. Create an Application under https://discord.com/developers/applications and get the Application ID br]
## 5. (optional) Set images under "Rich Presence" and "Art Assets" and remember the keys[br]
##
## This is your [code]_ready()[/code] function wich could be anywhere
## [codeblock]
func _ready():
	# Application ID
	DiscordRPC.app_id = 1099618430065324082
	# this is boolean if everything worked
	print("Discord working: " + str(DiscordRPC.get_is_discord_working()))
	# Set the first custom text row of the activity here
	DiscordRPC.details = "A demo activity by vaporvee#1231"
	# Set the second custom text row of the activity here
	DiscordRPC.state = "Checkpoint 23/23"
	# Image key for small image from "Art Assets" from the Discord Developer website
	DiscordRPC.large_image = "game"
	# Tooltip text for the large image
	DiscordRPC.large_image_text = "Try it now!"
	# Image key for large image from "Art Assets" from the Discord Developer website
	DiscordRPC.small_image = "boss"
	# Tooltip text for the small image
	DiscordRPC.small_image_text = "Fighting the end boss! D:"
	# "02:41 elapsed" timestamp for the activity
	DiscordRPC.start_timestamp = int(Time.get_unix_time_from_system())
	# "59:59 remaining" timestamp for the activity
	DiscordRPC.end_timestamp = int(Time.get_unix_time_from_system()) + 3600
	# Always refresh after changing the values!
	DiscordRPC.refresh()
## [/codeblock]
##
## @tutorial(More information here): https://github.com/vaporvee/discord-rpc-godot/wiki/Quick-start
## @tutorial(Make your Application ID and else here): https://discord.com/developers/applications
```

### Godot output

```shell
Discord working: false
```

### Additional information

Editor presence also doesn't seem to work, this is what i am getting.
```
- core/variant/variant_utility.cpp:1112 - EditorPresence couldn't be loaded! Maybe your Discord isn't running?
Set enabled
```
(I have Discord open as both app and in browser)

My system is:
  Kernel: 5.15.0-119-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.
- [X] I did read the documentation https://vaporvee.com/docs/discord-rpc-godot/

**Comment by vaporvee** [comment]
Browser would never work with it but did you install discord via flatpack?

**Comment by Variable-ind** [comment]
> Browser would never work with it but did you install discord via flatpack?

i think i did (let me check)

**Comment by Variable-ind** [comment]
Thank's for the quick response, it's now working with the (.deb) version.
Thanks soo much

**Comment by vaporvee** [comment]
nice glad i could help :) i will update the troubleshooting as son as possible because i have many duplicates recently
