### ISSUE TITLE
[Issue/Bug]: Rendering order messed up

### ISSUE THREAD

**Issue by Kesuaheli** [vaporvee/discord-rpc-godot#69]
### What happened?

As soon as I enable the plugin in the project settings I get a weird bug where my Buttons get rendered on top of other elements.

In particular I have this in the scene tree
![scene_tree](https://github.com/user-attachments/assets/2dbcd4bf-9773-4f18-b6f4-8155d1235a8a)
As you can see `Play`, `Options`, and `Quit` are Buttons, that are placed before the `RoundCreation`-CanvasLayer. If I enable the visibility of `RoundCreation` in the editor, it is correctly placed on top of the buttons (i.e. you can't see the buttons nor click them).
However, if I start this scene it looks like this:
The three buttons are placed on top of the `RoundCreation`. But they're not clickable. You can see them, but **can't** click them.
![ingame_screenshot](https://github.com/user-attachments/assets/f741c652-2d43-4748-a93f-5b5821e9c5dd)

### Version

1.3.1

### Godot Version

v4.2.1.stable.official [b09f793f5]

### Exact steps to reproduce this error

I haven't tried to reproduce this in a fresh project. If you want, our project is open sourced at ~~cake4everyone/Quiz4Everyone@`discord-presence`. Currently, the Discord plugin is only installed and enabled in this branch~~ ***See [comment below](https://github.com/vaporvee/discord-rpc-godot/issues/69#issuecomment-2351498200)***. If you want to try it, you have to start the `res://scenes/menu.tscn`-Scene (the one from the screenshot).

Once you disable die plugin in the project settings (dont even need to restart Godot Engine), it works fine again.

### GDScript

```gdscript
# nothing involved afaik
```

### Additional information

**Off Topic:**
The [third checkbox form the *Checks*](https://github.com/vaporvee/discord-rpc-godot/blob/3411e9a8700461395bdcf8533ab32004ef84f483/.github/ISSUE_TEMPLATE/BUG.yml?plain=1#L99) down below contains [this url](https://vaporvee.com/docs/discord-rpc-godot/) to a 404 page ;)
So... yes, I did read the 404 page, didn't help either ;)

I belive it should be updated to https://docs.vaporvee.com/discord-rpc-godot/ alternatively adjust your redirect (from `/docs` to your `docs` subdomain) to also include the `/discord-rpc-godot` part.

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.
- [X] I did read the documentation https://vaporvee.com/docs/discord-rpc-godot/

**Comment by vaporvee** [comment]
How is that even possible? it doesn't change stuff in the scene tree. but thank you for the testing project i will look into that really weird bug

**Comment by Kesuaheli** [comment]
Well okay, it has something todo with `RoundCreation` beeing a `CanvasLayer`-Node.
After I tried to manually forcing the render-order by changing the `z_index` (which didn't made any difference btw), I tried messing with the nodes themselfs.
Yea, if I dont have another `CanvasLayer` in the Scene, it works again.

**Comment by Kesuaheli** [comment]
Have fixed it in my branch with this commit https://github.com/cake4everyone/Quiz4Everyone/commit/584eb39c927a139910683e0d18c29ba74f5d27d9 btw. So the last non-working state is https://github.com/cake4everyone/Quiz4Everyone/tree/d3f5e2f6fa5d27e0541b481aad24c55eb5133328, if stil want to check
