### ISSUE TITLE
[Issue/Bug]: Avoiding "Discord Activity couldn't be updated" warning message

### ISSUE THREAD

**Issue by Yolwoocle** [vaporvee/discord-rpc-godot#71]
### What happened?

I call `DiscordRPC.refresh` every 3 seconds or so, but if Discord is not launched, I get the following warning message every time the function is called: 
```
Discord Activity couldn't be updated. It could be that Discord isn't running!
```

Now, this is fine, but is there any way to avoid having this warning message in the console, perhaps by detecting if Discord is launched/can be updated, and only calling `refresh` when needed.

### Version

1.3.1

### Godot Version

4.3.stable.official

### Exact steps to reproduce this error

Example reproduction code, should be ran while Discord isn't launched:

### GDScript

```gdscript
var _discord_rpc_update_timer = 0.0

func _ready():
    DiscordRPC.app_id = DISCORD_RPC_APP_ID

func _process(delta):
    _discord_rpc_update_timer -= delta
    if _discord_rpc_update_timer < 0:
        DiscordRPC.details = "Playing my incredible game"
        DiscordRPC.refresh()
        _discord_rpc_update_timer = 3.0
```

### Checks

- [X] I tried reinstalling the addon or tried to fix it myself with other methods.
- [X] I tried restarting Discord and Godot completely.
- [X] I did read the documentation https://vaporvee.com/docs/discord-rpc-godot/

**Comment by Yolwoocle** [comment]
This isn't a bug, more like an issue or suggestion.

**Comment by vaporvee** [comment]
Nope you are using it extremely wrong. You shouldn't refresh every 3 seconds first of all and also there is `DiscordRPC.get_is_discord_working()`. Refreshing it every 3 seconds overloads the rpc server and wouldn't work. Also why are you updating the same Activity all the time? Does it dissapear for some reason?

**Comment by Yolwoocle** [comment]
> Nope you are using it extremely wrong. You shouldn't refresh every 3 seconds

Okay, I come from a different DiscordRPC lib from a different language and this is how I did it there, I didn't expect it to be different here. What would be the correct way to do it?

> Refreshing it every 3 seconds overloads the rpc server and wouldn't work. Also why are you updating the same Activity all the time? Also why are you updating the same Activity all the time? Does it dissapear for some reason?

I'm updating things like the current level the player is in, whether the player is in a menu, which can change rapidly. Should I only update and refresh when there is an actual change? It seems to work though. Why would this overload the RPC servers?

> there is `DiscordRPC.get_is_discord_working()`

This is mentioned nowhere in the docs. I'd highly appreciate if there was a page in the docs with a complete reference of all the API's functions, it would be of great help. 😄

**Comment by vaporvee** [comment]
`DiscordRPC.get_is_discord_working()` is the only function missing in the docs will add that though. There is a `run_callbacks` in a autoload automatically installed which must be the thing you where seeing in other libs. Only update those things in signals if you can. The thing is the RPC server from Discord is really buggy. Its not reliable at all and a complete mess. When you rapidly change the activity and it still shows up or not doesn't mean it shows for other users so just do it the right way initially.

**Comment by Yolwoocle** [comment]
Okay, I see. I'll change my code in this case, thanks a lot for your help 👍

**Comment by vaporvee** [comment]
No problem :)
