### ISSUE TITLE
[Feature request]: Add buttons

### ISSUE THREAD

**Issue by BOXERRMD** [vaporvee/discord-rpc-godot#73]
### What is your idea?

Is it possible to add a configuration for the two buttons we can add to the RPC?

ex: 
![image](https://github.com/user-attachments/assets/f33adf2c-be29-4818-843e-8736789c8e9a)

Thanks !

**Comment by vaporvee** [comment]
Thats not possible with the Discord Game SDK. Only with a custom IPC library and that wouldn't be easy at all. Curseforge uses a fork of the old Discord RPC library i think but it was way to unstable with Godot so i used the newer official one. Btw use modrinth

**Comment by BOXERRMD** [comment]
Small additional question: how do you disconnect the RPC? I use the "clear" and "update" function but it works once out of 10

**Comment by vaporvee** [comment]
just use clear not update and the delay is only on client side.

**Comment by BOXERRMD** [comment]
Oh okay, thanks! 
I will share with you the application that I am making with your module and I will mention you on it
